import type { Metadata } from "next";
import "./scss/globals.scss";
import Header from "@/src/components/header/Header";
import StoreProvider from "@/src/Providers/ReduxProvider";
import { useSelector } from "react-redux";
import Footer from "@/src/components/footer/Footer";
import StateContext from "@/src/context/StateContext";

export const metadata: Metadata = {
  title: "Brush.Ish | Artist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <StateContext>
            <Header />
            <main>{children}</main>
            <Footer />
          </StateContext>
        </StoreProvider>
      </body>
    </html>
  );
}
